development:
  adapter: postgresql
  encoding: unicode
  database: imp_development
  pool: 5
  username: mashype
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: imp_test
  pool: 5
  username: mashype
  password:

production:
  database: <%= ENV["DATABASE_NAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  adapter: postgresql
  host: ec2-54-235-182-120.compute-1.amazonaws.com



